# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f523fca2bf92f34c1e8a247edd50528945d4203a25d6ecb1e528ecc2f7044565dab09d168890abc0f717ba6ceae372be7ff41b5c9834ac127cb7e2a6195349c2

test:
  secret_key_base: 3910fe004d408638583ef227787ec046f3e56269d30dcc7021f80064b40e40bac03b6ca7f55ffab1d7a725df65bcf46e6b8ee7c00e8b5d2c265ea49bb3d3db7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
